### PR TITLE
systray, thread, http

### PR DESCRIPTION
**Pull request by glurp**
Here my contributions.

I created a plugins directory under lib,
put into the differents contributions,
and add require_relative to them in green_shoes.rb.

then I put sample54.rb which use all of them. 
(but it show the memory leaks.)

All that is tested under windows 7.

I created as plugin because theses api seem to be specifique to green-shoes.

by

### CODE REVIEW

**Comment by ashbb** [comment]
Hi raubarede, 

Fantastic! Thank you for the great contribution!
Your sample54.rb worked fine on my Windows 7 when I did `ruby sample54.rb`.
But it was not launched from on built-in manual sample page.
Could you check it out?

ashbb

**Comment by glurp** [comment]
Thank you for your encouragement !

It's done with manual, but exit from sample54 do a exit of manual...

In green_shoes I adjust : 
- append :font in attrib for edit_box, 
- instance_eval with filename in help.rb

I wonder if creation of plugins directory was good : perhaps shoes/ext is the right place  ..?

by

**Comment by glurp** [comment]
done, in same pull request

2011/7/26 ashbb <
reply@reply.github.com>

> Hi raubarede,
> 
> Fantastic! Thank you for the great contribution!
> Your sample54.rb worked fine on my Windows 7 when I did `ruby sample54.rb`.
> But it was not launched from on built-in manual sample page.
> Could you check it out?
> 
> ashbb
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ashbb/green_shoes/pull/36#issuecomment-1653710

## 

---

---

|**) |**  / _` | /__`
|  \ |___ __> | .__/

---

**Comment by ashbb** [comment]
Great work! I've merged your commits. Thanks!!

**Pull request merged**
