### PR TITLE
Margins

### PR DESCRIPTION
**Pull request by ozpos**
Fixes to margins but borders are not drawn to the full width yet.

### CODE REVIEW

**Comment by ashbb** [comment]
@ozpos

Thanks for the full request. :)
I downloaded [your repo](https://github.com/ozpos/green_shoes) and tried to execute a few samples.
The samples/abctest.rb worked fine. But the samples/sample25.rb was failed... Could you confirm again?

**Comment by ozpos** [comment]
Hi ashbb,
Yes it fails for me also.

**Comment by ozpos** [comment]
Hi Ashbb,
Sorry, found the problem. sample25.rb is ok now.
How can I cancel the pull request and issue a new one ?
Still learning git!!
John

**Comment by ashbb** [comment]
No problem. Just close #77 and open a new one. :)

**Comment by ozpos** [comment]
Done.

**Pull request closed without merging**
